apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    # maintainer: bogdan.demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  # - name: cache-volume
  #   hostPath:
  #     path: /tmp